title = "UEC Daily Report"

[database]
sql_database = "Data_Lab_NCL_Dev"
sql_schema = "JakeK"
sql_cooloff = 60

[smart_api]

[smart_api.base]
sql_table = "smart_api_data_test"
api_url = "https://smart.nhs.uk/"
sites = ["S0189179","S89CFECF","S818235B","SF06F50A","S48446E1","S12C3F7C"]
#"S0189179" #Barnet Hospital
#"S89CFECF" #Chase Farm Hospital
#"S818235B" #North Middlesex Hospital
#"SF06F50A" #Royal Free Hospital
#"S48446E1" #UCLH
#"S12C3F7C"	#Whittington Hospital
indicator_list = ['breaches','no_of_attendances','dta_in_ed_at_time_of_reporting','medically_optimised']

[smart_api.date]
end = "today"
window = "2 weeks"

[smart_api.wait]
period = 5

[las]

[las.base]
sql_table = "uec_las_handover_test"
indicator_list = ['hospital_site','total_handover','over_45mins','over_120mins']

[ecist_sitrep]

[ecist_sitrep.base]
sql_table = "uec_sitrep_ecist_test"
indicator_list = ['ae_attendances','over12hoursfromarrival','extended_patients_occupied','g&acorebedsopen', 'number_of_discharges']
org_list = ['RAL','RAP','RRV','RKE']

[ecist_sitrep.date]
date_range = 35

