title = "UEC Daily Report"

[database]
sql_database = "Data_Lab_NCL_Dev"
sql_schema = "JakeK"
sql_cooloff = 60

[smart_api]

[smart_api.base]
sql_table = "uec_daily_smart"
api_url = "https://smart.nhs.uk/"
sites = ["S0189179","S89CFECF","S818235B","SF06F50A","S48446E1","S12C3F7C"]
#"S0189179" #Barnet Hospital
#"S89CFECF" #Chase Farm Hospital
#"S818235B" #North Middlesex Hospital
#"SF06F50A" #Royal Free Hospital
#"S48446E1" #UCLH
#"S12C3F7C"	#Whittington Hospital
indicator_list = ['breaches','no_of_attendances','dta_in_ed_at_time_of_reporting','medically_optimised']

[smart_api.date]
end = "today"
window = "2 weeks"

[smart_api.wait]
period = 5

[las]

[las.base]
sql_table = "uec_daily_las"
indicator_list = ['hospital_site','total_handover','over_45mins','over_120mins']
archive_file = 1
extract_number_of_days = 40
historic_load = 1
historic_schema = "JakeK"
historic_table = "uec_warehouse_las"
historic_indicators = ['hospital_site','total_handover','over_45mins','over_120mins']


[ecist_sitrep]

[ecist_sitrep.base]
sql_table = "uec_daily_ecist"
indicator_list = ['ae_attendances','over12hoursfromarrival','extended_patients_occupied','g&acorebedsopen', 'number_of_discharges']
org_list = ['RAL','RAP','RRV','RKE']
archive_file = 1
historic_load = 1
historic_schema = "JakeK"
historic_table = "uec_warehouse_ecist"
historic_indicators = ['ae_attendances','over12hoursfromarrival','extended_patients_occupied','g&acorebedsopen', 'number_of_discharges']

[ecist_sitrep.date]
date_range = 35

[live_tracker]
archive_file = 1

[live_tracker.mo]
mo = "Daily Delay"
mo_sheet_name = "NCL TOTAL"
mo_table_heading = "Total by Hospital"
mo_sql_table = "uec_daily_tracker_mo"
mo_date_overwrite = ""

[live_tracker.p2]
p2 = "P2 Capacity"
p2_sheet_name = "P2 Capacity"
p2_sql_table = "uec_daily_tracker_p2"
p2_date_overwrite = ""

[live_tracker.vw]
vw = "Virtual Ward"
vw_sheet_name = "Historic System Value"
vw_sql_table = "uec_daily_tracker_vw"

